[theme]
base="dark"
primaryColor="#4CAF50"
backgroundColor="#0E1117"      # Dark gray/black background
secondaryBackgroundColor="#1E222A"  # Slightly lighter cards/side-panels
textColor="#FAFAFA"            # Off-white text